-- 260225 과제 목록

-- 1. 지역별 부서의 수를 조회한다. (부서가 없으면 부서의 수는 0으로 조회한다.)
 SELECT L.CITY 
      , COUNT(D.DEPARTMENT_ID)
   FROM LOCATIONS L
   LEFT OUTER JOIN DEPARTMENTS D
     ON L.LOCATION_ID = D.LOCATION_ID 
  GROUP BY L.CITY 
  ORDER BY L.CITY ASC
;
-- 2. 지역별 사원의 평균월급을 조회한다. (사원이 없으면 평균월급은 0으로 조회한다.)
 SELECT L.CITY 
      , NVL(AVG(SALARY), 0)
   FROM LOCATIONS L
   LEFT OUTER JOIN DEPARTMENTS D
     ON L.LOCATION_ID = D.LOCATION_ID 
   LEFT OUTER JOIN EMPLOYEES E
     ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID 
  GROUP BY L.CITY 
  ORDER BY L.CITY ASC
;
-- 3. 도시명 별 사원의 수를 도시명으로 오름차순 정렬하여 조회한다.(사원이 없으면 사원의 수는 0으로 조회한다.)
 SELECT L.CITY 
      , COUNT(E.EMPLOYEE_ID)
   FROM LOCATIONS L
   LEFT OUTER JOIN DEPARTMENTS D
     ON L.LOCATION_ID = D.LOCATION_ID 
   LEFT OUTER JOIN EMPLOYEES E
     ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID 
  GROUP BY L.CITY 
  ORDER BY L.CITY ASC
 ;
  
-- 4. 모든 사원들의 현재 직무명과 과거의 직무명을 조회한다. 만약 직무가 한번도 변경되지 않았다면, 과거의 직무명은 '없음' 으로 조회한다.
SELECT E.FIRST_NAME || ' 현재 직무명 : ' ||J.JOB_TITLE || ' 과거 직무명 : ' || J.JOB_TITLE AS JOB_S
  FROM EMPLOYEES E
 INNER JOIN JOB_HISTORY JH 
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
 UNION ALL
SELECT EMP.FIRST_NAME || '현재 직무명 : ' || JO.JOB_TITLE  || ' 과거 직무명 : ' || ' 없음 '
  FROM EMPLOYEES EMP
 INNER JOIN JOBS JO
    ON JO.JOB_ID = EMP.JOB_ID 
 WHERE EMP.EMPLOYEE_ID NOT IN ( SELECT JHIS.EMPLOYEE_ID 
                                  FROM JOB_HISTORY JHIS)
 ORDER BY JOB_S ASC
;


-- 260224 과제 목록
-- 1. 100번 사원의 모든 부하직원을 계층조회한다.
 SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
   FROM EMPLOYEES
  START WITH EMPLOYEE_ID = 100
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
;
  
-- 2. 113번 사원의 모든 상사를 계층조회한다.
 SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
   FROM EMPLOYEES
  START WITH EMPLOYEE_ID = 113
CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID
;
-- 3. IT 부서장의 모든 부하직원을 계층조회한다.
 SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
   FROM EMPLOYEES
  START WITH EMPLOYEE_ID = (SELECT MANAGER_ID
                              FROM DEPARTMENTS
                             WHERE DEPARTMENT_NAME = 'IT'
                               AND ROWNUM = 1)
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID

-- 4. 부서장들의 부하직원을 계층조회한다.
 SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
   FROM EMPLOYEES
  START WITH EMPLOYEE_ID IN (SELECT MANAGER_ID
                              FROM DEPARTMENTS)
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID

-- 5. 부서명이 가장 긴 부서에서 근무중인 사원의 모든 정보를 조회한다.

SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
						  FROM (SELECT DEPARTMENT_ID
								     , LENGTH(DEPARTMENT_NAME)
								  FROM DEPARTMENTS
								 ORDER BY LENGTH(DEPARTMENT_NAME) DESC)
						 WHERE ROWNUM = 1)
; 
-- 6. 2002년부터 2006년까지 입사한 사원은 몇 명인지 연도별로 조회한다.

SELECT HIRE_YEAR
     , COUNT(EMPLOYEE_ID)
  FROM (SELECT TO_CHAR(HIRE_DATE, 'YYYY') AS HIRE_YEAR
		     , EMPLOYEE_ID
		  FROM EMPLOYEES)
  WHERE HIRE_YEAR BETWEEN 2002 AND 2006
  GROUP BY HIRE_YEAR
;
 

-- 7. 입사일이 가장 빠른 사원 5명의 이름과 입사일을 조회한다.
SELECT NAME
     , H_DATE
  FROM (SELECT NAME 
		     , H_DATE
		     , ROWNUM AS RN
		  FROM (SELECT FIRST_NAME AS NAME
				     , HIRE_DATE AS H_DATE
				  FROM EMPLOYEES
				 ORDER BY HIRE_DATE ASC))
 WHERE RN <=5
;
-- 8. 커미션을 받는 사원들의 이름과 커미션을 조회한다. 단, 커미션이 가장 높은 사원 3명은 제외한다.
SELECT NAME
     , COMMI
     , RN
  FROM (SELECT NAME
		     , COMMI
		     , ROWNUM AS RN
		  FROM (SELECT FIRST_NAME AS NAME
				     , COMMISSION_PCT AS COMMI
				  FROM EMPLOYEES
				 WHERE COMMISSION_PCT IS NOT NULL
				 ORDER BY COMMISSION_PCT DESC))
 WHERE RN > 3
;



-- 가장많은 월급을 받는 사원 한명만 조회한다
-- 기존 푸는 방식 :
SELECT EMPLOYEE_ID
  FROM EMPLOYEES
 WHERE SALARY = (SELECT MAX(SALARY)
                   FROM EMPLOYEES)
;
-- 다른 방식 :
SELECT * 
  FROM (SELECT * 
          FROM EMPLOYEES
         ORDER BY SALARY DESC)
 WHERE ROWNUM <= 5
;
  


-- 1. 모든 부서들의 정보와 도시 정보를 조회한다.
SELECT D.DEPARTMENT_ID
     , D.DEPARTMENT_NAME
     , D.MANAGER_ID
     , D.LOCATION_ID
     , L.CITY
  FROM DEPARTMENTS D
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
;
    
-- 2. 모든 사원들의 정보와 부서명을 조회한다.
SELECT E.EMPLOYEE_ID 
     , E.FIRST_NAME 
     , E.LAST_NAME 
     , E.EMAIL 
     , E.PHONE_NUMBER 
     , E.HIRE_DATE 
     , E.JOB_ID 
     , E.SALARY 
     , E.COMMISSION_PCT 
     , E.MANAGER_ID 
     , E.DEPARTMENT_ID 
     , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
-- 3. 111번 사원의 모든 정보와 부서명을 조회한다.
SELECT E.EMPLOYEE_ID 
     , E.FIRST_NAME 
     , E.LAST_NAME 
     , E.EMAIL 
     , E.PHONE_NUMBER 
     , E.HIRE_DATE 
     , E.JOB_ID 
     , E.SALARY 
     , E.COMMISSION_PCT 
     , E.MANAGER_ID 
     , E.DEPARTMENT_ID 
     , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE E.EMPLOYEE_ID = '111'
;
-- 4. 115번의 사원의 모든 정보와 부서명, 직무명을 조회한다.
SELECT E.EMPLOYEE_ID 
     , E.FIRST_NAME 
     , E.LAST_NAME 
     , E.EMAIL 
     , E.PHONE_NUMBER 
     , E.HIRE_DATE 
     , E.JOB_ID 
     , E.SALARY 
     , E.COMMISSION_PCT 
     , E.MANAGER_ID 
     , E.DEPARTMENT_ID 
     , D.DEPARTMENT_NAME 
     , J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID
 WHERE E.EMPLOYEE_ID = '115'
;
-- 5. 100번 사원의 모든 정보와 부서명, 직무명, 도시명을 조회한다.
SELECT E.EMPLOYEE_ID 
     , E.FIRST_NAME 
     , E.LAST_NAME 
     , E.EMAIL 
     , E.PHONE_NUMBER 
     , E.HIRE_DATE 
     , E.JOB_ID 
     , E.SALARY 
     , E.COMMISSION_PCT 
     , E.MANAGER_ID 
     , E.DEPARTMENT_ID 
     , D.DEPARTMENT_NAME 
     , J.JOB_TITLE 
     , L.CITY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
 WHERE E.EMPLOYEE_ID = '100'
;
-- 6. 부서명별 사원의 수를 조회한다.
SELECT D.DEPARTMENT_NAME
     , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
  
-- 7. 직무명별 사원의 평균월급을 조회한다.
 SELECT JOB_TITLE
      , AVG(SALARY)
   FROM EMPLOYEES E 
  INNER JOIN JOBS J
     ON E.JOB_ID = J.JOB_ID 
  GROUP BY J.JOB_TITLE 
 
-- 8. 부서명, 직무명별 사원의 수와 평균월급을 조회한다.
  SELECT D.DEPARTMENT_NAME
       , J.JOB_TITLE
       , COUNT(E.EMPLOYEE_ID)
       , AVG(SALARY)
    FROM EMPLOYEES E
   INNER JOIN DEPARTMENTS D
      ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
   INNER JOIN JOBS J
      ON E.JOB_ID = J.JOB_ID 
   GROUP BY D.DEPARTMENT_NAME 
       , J.JOB_TITLE 
;
-- 9. 부서명별 평균월급을 부서명으로 내림차순 정렬하여 조회한다.
  SELECT D.DEPARTMENT_NAME 
       , AVG(SALARY)
    FROM EMPLOYEES E
   INNER JOIN DEPARTMENTS D
      ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
   GROUP BY D.DEPARTMENT_NAME
   ORDER BY D.DEPARTMENT_NAME  DESC
;
-- 10. 부서명별 최고월급을 최고월급으로 오름차순 정렬하여 조회한다.
  SELECT D.DEPARTMENT_NAME
       , MAX(E.SALARY )
    FROM EMPLOYEES E 
   INNER JOIN DEPARTMENTS D 
      ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
   GROUP BY D.DEPARTMENT_NAME
   ORDER BY MAX(E.SALARY) ASC 
   ;
-- 11. 도시명 별 사원의 수를 도시명으로 오름차순 정렬하여 조회한다.
  SELECT C.CITY 
       , COUNT(E.EMPLOYEE_ID)
    FROM EMPLOYEES E
   INNER JOIN DEPARTMENTS D 
      ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
   INNER JOIN LOCATIONS C
      ON C.LOCATION_ID  = D.LOCATION_ID 
   GROUP BY C.CITY 
   ORDER BY C.CITY 
   ;
-- 12. 도시별 부서의 수를 조회한다.
SELECT L.CITY 
     , COUNT(D.DEPARTMENT_ID)
  FROM DEPARTMENTS D
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID  = L.LOCATION_ID 
 GROUP BY L.CITY 
;
-- 13. 도시별 사원의 평균월급을 조회한다.
 SELECT L.CITY 
      , AVG(SALARY)
   FROM EMPLOYEES E
  INNER JOIN DEPARTMENTS D
     ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
  INNER JOIN LOCATIONS L
     ON D.LOCATION_ID  = L.LOCATION_ID 
  GROUP BY L.CITY 
 

-- 최 상위 직원의 모든 직원들의 사원번호, 이름, 상사사원번호 계단(계층)식으로 조회한다 
SELECT LEVEL
     , EMPLOYEE_ID
     , FIRST_NAME
     , MANAGER_ID
  FROM  EMPLOYEES
 START WITH MANAGER_ID IS NULL 
 CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
;  

-- GROUP + JOIN

-- STEP1. 직무명별 수행중인 사원의 수 조회
SELECT JOB_ID
     , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 GROUP BY JOB_ID
;

SELECT J.JOB_TITLE E
     , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
 GROUP BY J.JOB_TITLE
;

-- STEP2. 도시별 근무중인 사원의 수 조회
SELECT L.CITY
     , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID
 GROUP BY L.CITY
;


-- STEP3. 도시별, 부서별 근무중인 사원의 수 조회
SELECT L.CITY
     , D.DEPARTMENT_NAME
     , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID
 GROUP BY L.CITY 
     , D.DEPARTMENT_NAME E
;



-- JOIN 연습문제
-- 사원의 이름과 성, 근무중인 부서 번호와 부서명을 조회한다 ('교' 집합)

SELECT E.FIRST_NAME
     , E.LAST_NAME 
     , D.DEPARTMENT_ID
     , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;

-- 사원의 이름과 성, 월급, 수행중인 직무의 아이디, 직무의 이름, 직무별 최대 월급 조회
SELECT E.FIRST_NAME 
     , E.LAST_NAME
     , E.SALARY
     , J.JOB_ID 
     , J.JOB_TITLE 
     , J.MAX_SALARY 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
;

-- 사원의 이름, 사원 번호, 수행중인 직무의 이름, 근무중인 부서의 이름을 조회
SELECT E.FIRST_NAME 
     , E.LAST_NAME 
     , J.JOB_TITLE
     , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
;

-- 사원의 번호, 이름, 성 , 이메일과 근무중인 도시의 이름 조회
SELECT E.EMPLOYEE_ID 
     , E.FIRST_NAME
     , E.LAST_NAME
     , E.EMAIL 
     , L.CITY
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
;

-- 모든 사원들의 이름, 상사의 사원번호, 상사의 사원명을 조회
SELECT E.EMPLOYEE_ID
     , U.EMPLOYEE_ID 
     , U.FIRST_NAME 
  FROM EMPLOYEES E
 INNER JOIN EMPLOYEES U
    ON E.MANAGER_ID  = U.EMPLOYEE_ID 
;

-- 사원이 수행중인 직무의 이름, 상사가 수행중인 직무의 이름을 조회한다
 SELECT E.EMPLOYEE_ID
     , EJ.JOB_ID AS EMPLOYEE_JOB_ID
     , U.EMPLOYEE_ID 
     , EU.JOB_ID AS UPPER_JOB_ID
     , U.FIRST_NAME 
  FROM EMPLOYEES E
 INNER JOIN EMPLOYEES U
    ON E.MANAGER_ID  = U.EMPLOYEE_ID 
 INNER JOIN JOBS EJ
    ON E.JOB_ID = EJ.JOB_ID 
 INNER JOIN JOBS EU
    ON U.JOB_ID = EU.JOB_ID 
;
 
-- SUB QUERY 연습문제
-- 최고 월급을 받는 사원들의 사원 번호와 월급을 조회한다
-- > 내가 모르는것 ? 은 ? [최고 월급] < SALARY
SELECT MAX(SALARY)
  FROM EMPLOYEES
;
-- > 24,000$ 
SELECT EMPLOYEE_ID
     , SALARY
  FROM EMPLOYEES
 WHERE SALARY = 24000
;
--> 합치기
SELECT EMPLOYEE_ID
     , SALARY
  FROM EMPLOYEES
 WHERE SALARY = (SELECT MAX(SALARY)
 				   FROM EMPLOYEES)
;

-- 평균 월급보다 적게 받는 사원들의 사원번호와 월급을 조회한다
-- 내가 모르는것 : [평균 월급] 
SELECT EMPLOYEE_ID
     , SALARY
  FROM EMPLOYEES
 WHERE SALARY < (SELECT AVG(SALARY)
 				   FROM EMPLOYEES) 
;

-- 수행하는 직무의 이름이 'FINANCE MANAGER' 인 사원의 사원 번호와 직무 아이디를 조회한다 
SELECT EMPLOYEE_ID
     , JOB_ID
  FROM EMPLOYEES
 WHERE JOB_ID = (SELECT JOB_ID
				   FROM JOBS
			 	  WHERE JOB_TITLE = 'Finance Manager')
;

-- SEATTLE 에서 근무중인 사원들의 이름 성 부서 번호를 조회한다
-- [SEATTLE 지역 번호]
-- [SEATTLE 의 부서번호]
-- SEATTLE에 있는 부서들 번호가 무엇인지 안다면 사원들의 성 이름 부서번호를 조회할 수 있다
SELECT DEPARTMENT_ID
  FROM DEPARTMENTS
 WHERE LOCATION_ID = (SELECT LOCATION_ID
	   			 	    FROM LOCATIONS
     			       WHERE CITY = 'Seattle')
;

SELECT FIRST_NAME
     , LAST_NAME
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN ((SELECT DEPARTMENT_ID
						  FROM DEPARTMENTS
	                      WHERE LOCATION_ID = (SELECT LOCATION_ID
							   			 	     FROM LOCATIONS
							     			    WHERE CITY = 'Seattle')
))


-- 1. 모든 사원의 모든 정보를 조회한다. 결과 수 : 107
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
;
-- 2. 부서가 없는 사원의 모든 정보를 조회한다. 결과 수 : 1
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IS NULL 
;
-- 3. 직무가 없는 사원의 모든 정보를 조회한다. 결과 수 :  0
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE JOB_ID IS NULL 
;
-- 4. 부서와 직무가 모두 있는 사원의 모든 정보를 조회한다. 결과 수 :  106 
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IS NOT NULL 
   AND JOB_ID IS NOT NULL
;
-- 5. 부서장이 없는 모든 부서의 모든 정보를 조회한다. 결과 수 : 16
SELECT DEPARTMENT_ID
     , DEPARTMENT_NAME
     , MANAGER_ID
     , LOCATION_ID
  FROM DEPARTMENTS
  WHERE MANAGER_ID IS NULL 
;
-- 6. 부서장이 있는 모든 부서의 모든 정보를 조회한다. 결과 수 : 11
SELECT DEPARTMENT_ID
     , DEPARTMENT_NAME
     , MANAGER_ID
     , LOCATION_ID
  FROM DEPARTMENTS
  WHERE MANAGER_ID IS NOT NULL 
;
-- 7. 사원의 이름만 조회한다. 결과 수 : 107
SELECT FIRST_NAME -- 이름조회
 FROM EMPLOYEES
;
-- 8. 모든 지역의 모든 정보를 조회한다. 결과 수 : 23
SELECT LOCATION_ID
     , STREET_ADDRESS
     , POSTAL_CODE
     , CITY
     , STATE_PROVINCE
     , COUNTRY_ID
 FROM LOCATIONS -- 지역은 REGIONS가 아니라 LOCATIONS
;
-- 9. 지역이 없는 모든 부서의 정보를 조회한다. 결과 수 : 0
SELECT DEPARTMENT_ID
     , DEPARTMENT_NAME
     , MANAGER_ID
     , LOCATION_ID
  FROM DEPARTMENTS
  WHERE LOCATION_ID IS NULL 
;


---- 추가 문제

-- 1. (12건) 부서아이디별 사원의 평균연봉을 조회한다.
SELECT AVG(SALARY) 
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
;

-- 2. (19건) 직무아이디별 사원의 최고연봉을 조회한다.
SELECT MAX(SALARY)
  FROM EMPLOYEES
 GROUP BY JOB_ID 
;

-- 3. (72건) 인센티브를 안받는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NULL
;

-- 4. (2건) 인센티브를 받는 사원의 부서아이디를 중복없이 조회한다.
SELECT DISTINCT DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL
;

-- 5. (2건) 인센티브를 받는 사원의 직무아이디를 중복없이 조회한다.
SELECT DISTINCT JOB_ID 
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL
;

-- 6. (7건) 사원이 있는 부서의 지역아이디를 조회한다.
SELECT DISTINCT LOCATION_ID
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
 						   FROM EMPLOYEES
 						  WHERE EMPLOYEE_ID IS NOT NULL
 )
;

-- 7. (21건) Seattle에 존재하는 부서번호를 조회한다.
SELECT DEPARTMENT_ID
  FROM DEPARTMENTS
 WHERE LOCATION_ID IN (SELECT LOCATION_ID 
 						 FROM LOCATIONS
 						WHERE CITY = 'Seattle')
;
-- 8. (16건) 사원이 한명도 없는 도시를 조회한다.
SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID NOT IN (SELECT LOCATION_ID
    					 FROM DEPARTMENTS
    					WHERE DEPARTMENT_ID IN ( SELECT DEPARTMENT_ID 
    											   FROM EMPLOYEES 
    											)
    				)
;

-- 9. (7건) 사원이 한명이라도 있는 도시를 조회한다.
SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID IN (SELECT LOCATION_ID
    					 FROM DEPARTMENTS
    					WHERE DEPARTMENT_ID IN ( SELECT DEPARTMENT_ID 
    											   FROM EMPLOYEES 
    											)
    				)
;

-- 10. (107건) 모든 사원의 정보를 연봉으로 오름차순 정렬하여 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 ORDER BY SALARY ASC
;


-- 11. (107건) 모든 사원의 사원번호, 이름, 성, 연봉, 인센티브를 포함한 연봉 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , SALARY
     , SALARY + (SALARY * NVL((COMMISSION_PCT), 0)) AS TOTAL_SALARY
  FROM EMPLOYEES
;

-- 12. (6건) 2003년에 입사한 사원은 몇 명인지 조회한다.
SELECT COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '2003'
;

-- 13. (1건) 113번 사원의 상사의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID
                         FROM EMPLOYEES
                        WHERE EMPLOYEE_ID = '133')
;

-- 14. (11건) 모든 부서의 부서장의 모든 사원 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID
                         FROM DEPARTMENTS )

-- 15. (23건) 사원의 이름이 7자리인 사원의 모든 정보를 조회한다.
 SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '_______'
;
                         
-- 16. (25건) 사원의 이메일이 6자리인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE EMAIL LIKE '______'
;

-- 1. 현재 시간을 조회한다.
SELECT SYSDATE 
  FROM DUAL
;

-- 1-1 오늘을 기준으로 하루 전의 날짜와 시간을 조회한다
SELECT SYSDATE - 1
  FROM DUAL
;
-- 1-2 현재시간을 기준으로 3시간 전의 날짜와 시간을 조회
SELECT SYSDATE - 3/24
  FROM DUAL
; 
-- 1-3 현재시간을 기준으로 15분 전의 날짜와 시간을 조회
-- 1-4 현재 시간을 기준으로 50초 후의 날짜와 시간을 조회
SELECT SYSDATE + 50/24/60/60
	 , SYSDATE
  FROM DUAL
;
-- 1-5 현재 시간을 기준으로 한달 이후 시간을 조회
SELECT ADD_MONTHS(SYSDATE, 1)
  FROM DUAL
;
-- 1-6 현재 시간을 기준으로 1년 이후 시간을 조회
SELECT ADD_MONTHS(SYSDATE, 12)
  FROM DUAL
;
-- 2. 현재 시간을 "연-월-일" 포멧으로 조회한다.
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
  FROM DUAL
;
-- 3. 한 시간 전 시간을 "시:분:초" 포멧으로 조회한다.
SELECT TO_CHAR(SYSDATE - 1 /24 , 'HH24:MI:SS')
  FROM DUAL
;
-- 2월 12일 연습문제  
-- '2026-02-12' text를 날짜 타입으로 변경한다
SELECT TO_DATE('2026-02-12', 'YYYY-MM-DD')
  FROM DUAL
;
-- '2026-02-12' 기준으로 50일 이후 날짜와 시간을 조회한ㄷ 
SELECT TO_DATE('2026-02-12', 'YYYY-MM-DD') + 50
  FROM DUAL
;
-- '2026-02-13' 기준으로 3시간 이후 날짜와 시간을  조회한ㄷ 
SELECT TO_DATE('2026-02-12', 'YYYY-MM-DD') + 3/24
  FROM DUAL
;
-- '2026-02-12' 기준으로 하루 이후 날짜만 시간을 조회한ㄷ
SELECT  TO_CHAR(TO_DATE('2026-02-12', 'YYYY-MM-DD') + 1, 'YYYY-MM-DD' )
  FROM DUAL
;
-- '2026-02-12' 기준으로 3일 후의 날짜와 시만 저회;한다
 SELECT TO_CHAR(TO_DATE('2026-02-12', 'YYYY-MM-DD') + 3, 'YYYY-MM-DD:HH24')
   FROM DUAL
;  
 -- 3 달 추가 
SELECT ADD_MONTHS(TO_DATE('2026-02-12', 'YYYY-MM-DD'), 3)
  FROM DUAL
;
-- 4. EMPLOYEES 테이블의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
;
-- 5. DEPARTMENTS 테이블의 모든 정보를 조회한다.
SELECT DEPARTMENT_ID 
     , DEPARTMENT_NAME 
     , MANAGER_ID
     , LOCATION_ID 
  FROM DEPARTMENTS
;
-- 6. JOBS 테이블의 모든 정보를 조회한다.
SELECT JOB_ID
     , JOB_TITLE 
     , MIN_SALARY
     , MAX_SALARY  
  FROM JOBS
;
-- 7. LOCATIONS 테이블의 모든 정보를 조회한다.
SELECT LOCATION_ID 
     , STREET_ADDRESS 
     , POSTAL_CODE
     , CITY
     , STATE_PROVINCE 
     , COUNTRY_ID
  FROM LOCATIONS
;
-- 8. COUNTRIES 테이블의 모든 정보를 조회한다.
SELECT COUNTRY_ID 
     , COUNTRY_NAME ME
     , REGION_ID
  FROM COUNTRIES
;
-- 9. REGIONS 테이블의 모든 정보를 조회한다.
SELECT REGION_ID 
     , REGION_NAME
  FROM REGIONS
;
-- 10. JOB_HISTORY 테이블의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , START_DATE 
	 , END_DATE
	 , JOB_ID , DEPARTMENT_ID 
  FROM JOB_HISTORY
;
-- 11. 90번 부서에서 근무하는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY
     , COMMISSION_PCT
     , MANAGER_ID
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 90
;
-- 12. 90번, 100번 부서에서 근무하는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 90 
  	OR DEPARTMENT_ID = 100
;
-- 13. 100번 상사의 직속 부하직원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
 WHERE MANAGER_ID = 100
;
-- 14. 직무 아이디가 AD_VP 인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
 WHERE JOB_ID = 'AD_VP'
;
-- 15. 월급이 7000 이상인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
 WHERE SALARY >= 7000
;
-- 16. 2005년 09월에 입사한 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID	
  FROM EMPLOYEES
 WHERE HIRE_DATE >= TO_DATE('2005-09-01' , 'YYYY-MM-DD') 
   AND HIRE_DATE < TO_DATE('2005-10-01' , 'YYYY-MM-DD')
;
-- BETWEEN 사용 
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID	
  FROM EMPLOYEES
 WHERE HIRE_DATE BETWEEN TO_DATE('2005-09-01' , 'YYYY-MM-DD') AND TO_DATE('2005-10-01' , 'YYYY-MM-DD') - 1
;

-- 17. 111번 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 111
;
-- 18. 인센티브를 안받는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NULL
;
-- 19. 인센티브를 받는 사원들의 모든 정보를 조회다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL
;
-- 20. 이름의 첫 글자가 'D' 인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'D%'
;
-- 21. 성의 마지막 글자가 'a' 인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE LAST_NAME LIKE '%a'
;
-- 22. 전화번호에 '.124.'이 포함된 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '%.124.%'
;

-- 23. 직무 아이디가 'PU_CLERK'인 사원 중 월급이 3000 이상인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE JOB_ID = 'PU_CLERK' 
  AND SALARY >= 3000
;
-- 24. 평균 월급보다 많이 받는 사원들의 사원번호, 이름, 성, 월급을 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , SALARY
  FROM EMPLOYEES
 WHERE SALARY > (SELECT AVG(SALARY)
 				   FROM EMPLOYEES)
;
  
-- 25. 평균 월급보다 적게 받는 사원들의 사원번호, 월급, 부서번호를 조회한다.
SELECT EMPLOYEE_ID
     , SALARY
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE SALARY < (SELECT AVG(SALARY)
 				   FROM EMPLOYEES)
;

-- 26. 가장 많은 월급을 받는 사원의 사원번호, 이름, 월급을 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , SALARY
  FROM EMPLOYEES
 WHERE SALARY = (SELECT MAX(SALARY)
 				   FROM EMPLOYEES)
;
-- 27. 이름이 4글자인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE FIRST_NAME LIKE '____'
;
-- EXTREA 이름이 4글자 이상인 사원의 모든 정보 조회
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE FIRST_NAME LIKE '____%'
;

-- 28. 'SA_REP' 직무인 사원 중 가장 높은 월급과 가장 낮은 월급을 조회한다.
SELECT MAX(SALARY)
	 , MIN(SALARY)
  FROM EMPLOYEES
 WHERE JOB_ID = 'SA_REP'
;
-- 29. 사원의 입사일자를 '연-월-일' 형태로 조회한다.
SELECT TO_CHAR(HIRE_DATE, 'YYYY-MM-DD')
  FROM EMPLOYEES
;
-- 30. 가장 늦게 입사한 사원의 모든 정보를 조회한다.
SELECT  EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE HIRE_DATE = (SELECT MAX(HIRE_DATE)
 				      FROM EMPLOYEES)
;

-- 31. 가장 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT  EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE HIRE_DATE = (SELECT MIN(HIRE_DATE)
 				      FROM EMPLOYEES)
;
-- 32. 자신의 상사보다 더 많은 월급을 받는 사원의 모든 정보를 조회한다.
SELECT  EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES EMP
 WHERE SALARY > (SELECT SALARY
 				   FROM EMPLOYEES DEP
 				  WHERE DEP.EMPLOYEE_ID = EMP.MANAGER_ID)
;

-- 33. 자신의 상사보다 더 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT  EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES EMP
 WHERE HIRE_DATE < (SELECT HIRE_DATE 
 				   FROM EMPLOYEES DEP
 				  WHERE DEP.EMPLOYEE_ID = EMP.MANAGER_ID)
;

-- 34. 부서아이디별 평균 월급을 조회한다.
SELECT DEPARTMENT_ID
     , AVG(SALARY)
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
;
-- 35. 직무아이디별 평균 월급, 최고월급, 최저월급을 조회한다.
SELECT JOB_ID
     , AVG(SALARY)
     , MAX(SALARY)
     , MIN(SALARY)
 FROM EMPLOYEES
GROUP BY JOB_ID
;
-- 36. 가장 많은 인센티브를 받는 사원의 모든 정보를 조회한다.
SELECT  EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES EMP
 WHERE COMMISSION_PCT = (SELECT MAX(COMMISSION_PCT)
 				          FROM EMPLOYEES)
;
-- 37. 가장 적은 인센티브를 받는 사원의 월급과 인센티브를 조회한다.
SELECT  EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES EMP
 WHERE COMMISSION_PCT = (SELECT MIN(COMMISSION_PCT)
 				          FROM EMPLOYEES)
;
-- 38. 직무아이디별 사원의 수를 조회한다.
SELECT JOB_ID
     , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 GROUP BY JOB_ID
;

-- 39. 상사아이디별 부하직원의 수를 조회한다. 단, 부하직원이 2명 이하인 경우는 제외한다.
SELECT MANAGER_ID
     , COUNT(MANAGER_ID)
  FROM EMPLOYEES
 GROUP BY MANAGER_ID
HAVING COUNT(EMPLOYEE_ID) > 2
;
-- 40. 사원이 속한 부서의 평균월급보다 적게 받는 사원의 모든 정보를 조회한다.
SELECT  EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES EMP
 WHERE SALARY < (SELECT AVG(SALARY) 
 				   FROM EMPLOYEES DEP
 				  WHERE DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID)
;   
-- 41. 사원이 근무하는 부서명, 이름, 성을 조회한다.
SELECT D.DEPARTMENT_ID 
     , E.FIRST_NAME 
     , E.LAST_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
-- 42. 가장 적은 월급을 받는 사원의 부서명, 이름, 성, 월급, 부서장사원번호를 조회한다.
SELECT D.DEPARTMENT_NAME E 
     , E.FIRST_NAME 
     , E.LAST_NAME 
     , E.SALARY 
     , E.MANAGER_ID 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE E.SALARY = (SELECT MIN(SALARY)
                     FROM EMPLOYEES)
;
-- 43. 상사사원번호를 중복없이 조회한다.
-- 44. 50번 부서의 부서장의 이름, 성, 월급을 조회한다.
SELECT FIRST_NAME
     , LAST_NAME
     , SALARY
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = (SELECT MANAGER_ID
 					    FROM DEPARTMENTS
 					   WHERE DEPARTMENT_ID = 50)
;

-- 45. 부서명별 사원의 수를 조회한다.
SELECT DEPARTMENT_NAME
     , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY DEPARTMENT_NAME
;
-- 46. 사원의 수가 가장 많은 부서명, 사원의 수를 조회한다.
SELECT DEPARTMENT_NAME 
     , CNT
  FROM ( SELECT D.DEPARTMENT_NAME 
		      , COUNT(E.EMPLOYEE_ID ) AS CNT
		   FROM EMPLOYEES E
		  INNER JOIN DEPARTMENTS D
		     ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
		  GROUP BY D.DEPARTMENT_NAME 
		  ORDER BY CNT DESC)
  WHERE ROWNUM = 1
;
    
-- 47. 사원이 없는 부서명을 조회한다.
SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID NOT IN   (SELECT DEPARTMENT_ID
							     FROM EMPLOYEES
							    GROUP BY DEPARTMENT_ID
							   HAVING COUNT(DEPARTMENT_ID) >0 )
;

 
-- 48. 직무가 변경된 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID
					    FROM JOB_HISTORY)
;


-- 49. 직무가 변경된적 없는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID
					    FROM JOB_HISTORY)
;
-- 50. 직무가 변경된 사원의 과거 직무명과 현재 직무명을 조회한다.
SELECT DISTINCT J.EMPLOYEE_ID 
     , JS.JOB_TITLE AS OLD_JOB
     , JAS.JOB_TITLE AS CURRENT_JOB
  FROM EMPLOYEES E
 INNER JOIN JOB_HISTORY J
    ON E.EMPLOYEE_ID = J.EMPLOYEE_ID
 INNER JOIN JOBS JS
    ON JS.JOB_ID = J.JOB_ID 
 INNER JOIN JOBS JAS
    ON JAS.JOB_ID = E.JOB_ID 
;  

-- 51. 직무가 가장 많이 변경된 부서의 이름을 조회한다.

SELECT DEPARTMENT_NAME
  FROM ( SELECT J.DEPARTMENT_ID 
		      , D.DEPARTMENT_NAME 
		      , COUNT(J.EMPLOYEE_ID) AS EMP_COUNT
		   FROM JOB_HISTORY J 
		  INNER JOIN DEPARTMENTS D
		     ON J.DEPARTMENT_ID = D.DEPARTMENT_ID 
		  GROUP BY J.DEPARTMENT_ID 
		      , D.DEPARTMENT_NAME 
		  ORDER BY COUNT(J.EMPLOYEE_ID) DESC) 
 WHERE EMP_COUNT = (SELECT MAX(EMP_COUNT)
					  FROM ( SELECT J.DEPARTMENT_ID 
							      , D.DEPARTMENT_NAME 
							      , COUNT(J.EMPLOYEE_ID) AS EMP_COUNT
							   FROM JOB_HISTORY J 
							  INNER JOIN DEPARTMENTS D
							     ON J.DEPARTMENT_ID = D.DEPARTMENT_ID 
							  GROUP BY J.DEPARTMENT_ID 
							      , D.DEPARTMENT_NAME 
							  ORDER BY COUNT(J.EMPLOYEE_ID) DESC))
 ;



-- 52. 'Seattle' 에서 근무중인 사원의 이름, 성, 월급, 부서명 을 조회한다.
SELECT E.FIRST_NAME
     , E.LAST_NAME
     , E.SALARY
     , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE L.CITY = 'Seattle'
;
    
-- 53. 'Seattle' 에서 근무하지 않는 모든 사원의 이름, 성, 월급, 부서명, 도시를 조회한다.
SELECT E.FIRST_NAME
     , E.LAST_NAME
     , E.SALARY
     , D.DEPARTMENT_NAME
     , L.CITY
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE L.CITY != 'Seattle'
;
-- 54. 근무중인 사원이 가장 많은 도시와 사원의 수를 조회한다.  
SELECT CITY
     , EMP_COUNT
  FROM (SELECT L.CITY AS CITY
		     , COUNT(EMPLOYEE_ID) AS EMP_COUNT
		  FROM LOCATIONS L
		 INNER JOIN DEPARTMENTS D
		    ON L.LOCATION_ID = D.LOCATION_ID 
		 INNER JOIN EMPLOYEES E
		    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
		 GROUP BY L.CITY
		 ORDER BY COUNT(EMPLOYEE_ID) DESC)
 WHERE ROWNUM = 1
;



-- 55. 근무중인 사원이 없는 도시를 조회한다.
-- 56. 월급이 7000 에서 12000 사이인 사원이 근무중인 도시를 조회한다.
SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID IN  (SELECT LOCATION_ID 
						  FROM DEPARTMENTS 
						 WHERE DEPARTMENT_ID IN (SELECT DISTINCT  DEPARTMENT_ID
												   FROM EMPLOYEES
												  WHERE SALARY BETWEEN 7000 AND 12000 ))
;
-- 57. 'Seattle' 에서 근무중인 사원의 직무명을 중복없이 조회한다.
SELECT DISTINCT JOB_TITLE
  FROM JOBS
 WHERE JOB_ID IN ( SELECT JOB_ID
				     FROM EMPLOYEES
				    WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
											  FROM DEPARTMENTS
											 WHERE LOCATION_ID IN  ( SELECT LOCATION_ID
																	   FROM LOCATIONS 
																	  WHERE CITY = 'Seattle'))
) 

-- 직무명 JOBS
SELECT JOB_TITLE
  FROM JOBS
 WHERE JOB_ID IN () 

-- 근무중인 사원
 SELECT JOB_ID
   FROM EMPLOYEES
  WHERE DEPARTMENT_ID IN ()

-- 부서 위치 
SELECT DEPARTMENT_ID
  FROM DEPARTMENTS
 WHERE LOCATION_ID IN ()

 -- Seattle 위치
 SELECT LOCATION_ID
   FROM LOCATIONS 
  WHERE CITY = 'Seattle'
;
 
-- 58. 사내의 최고월급과 최저월급의 차이를 조회한다.
SELECT MAX(SALARY) - MIN(SALARY)
  FROM EMPLOYEES
;

-- 59. 이름이 'Renske' 인 사원의 월급과 같은 월급을 받는 사원의 모든 정보를 조회한다. 단, 'Renske' 사원은 조회에서 제외한다.

SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE FIRST_NAME != 'Renske'
  AND SALARY IN (
					SELECT SALARY
					  FROM EMPLOYEES
					 WHERE SALARY = (
									SELECT SALARY
									  FROM EMPLOYEES
									 WHERE FIRST_NAME = 'Renske'
				 ));


-- 모든 정보 출력
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE SALARY IN ( )

-- 월급 비교
SELECT SALARY
  FROM EMPLOYEES
 WHERE SALARY = ()

--  RENSKE
SELECT SALARY
  FROM EMPLOYEES
 WHERE FIRST_NAME = 'Renske'
;


-- 60. 회사 전체의 평균 월급보다 많이 받는 사원들 중 이름에 'u' 가 포함된 사원과 동일한 부서에서 근무중인 사원들의 모든 정보를 조회한다.

SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
						  FROM EMPLOYEES
						 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
											    FROM EMPLOYEES
											   WHERE FIRST_NAME LIKE '%u%')	)
  AND SALARY > (SELECT AVG(SALARY)
  	              FROM EMPLOYEES)           
;    

SELECT DEPARTMENT_ID
     , FIRST_NAME
     , SALARY
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%u%'
;

SELECT AVG(SALARY)
  FROM EMPLOYEES
;
-- 회사월급 많이받는 사람이 근무중인 부서
SELECT DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE SALARY > (SELECT AVG(SALARY) 
 				   FROM EMPLOYEES)
;

-- 이름에 에 'u' 가 포함된 사원과 동일한 부서 ? 

-- 이름에 U 자 들어가는 사람이 있는 부서
SELECT DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%u%'
;


-- 61. 부서가 없는 국가명을 조회한다.
SELECT COUNTRY_NAME
  FROM COUNTRIES
 WHERE COUNTRY_ID NOT IN (SELECT COUNTRY_ID FROM LOCATIONS WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM DEPARTMENTS)) 
;

-- 부서가 있는 국가명 ?
SELECT LOCATION_ID 
  FROM DEPARTMENTS 
;

SELECT LOCATION_ID
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IS NULL
;
-- 62. 'Europe' 에서 근무중인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
						  FROM DEPARTMENTS
	                      WHERE LOCATION_ID IN (SELECT LOCATION_ID
							   			 	     FROM LOCATIONS
							     			    WHERE COUNTRY_ID IN  (SELECT COUNTRY_ID
																	  FROM COUNTRIES
																	 WHERE REGION_ID = (SELECT REGION_ID
																						  FROM REGIONS
																						 WHERE REGION_NAME =  'Europe'))))
;
-- 63. 'Europe' 에서 가장 많은 사원들이 있는 부서명을 조회한다.
SELECT DEPAR_NAME
  FROM ( SELECT D.DEPARTMENT_NAME  AS DEPAR_NAME
		      , COUNT(E.EMPLOYEE_ID ) AS EMP_COUNT
		   FROM EMPLOYEES E
		  INNER JOIN DEPARTMENTS D
		     ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
		  WHERE D.LOCATION_ID IN ( SELECT LOCATION_ID
								     FROM LOCATIONS L
								    WHERE COUNTRY_ID IN (SELECT COUNTRY_ID
														    FROM COUNTRIES
														   WHERE REGION_ID = (SELECT REGION_ID
																				  FROM REGIONS 
																			     WHERE REGION_NAME = 'Europe')))
		 GROUP BY D.DEPARTMENT_NAME 
		 ORDER BY COUNT(E.EMPLOYEE_ID) DESC)
WHERE ROWNUM = 1
;

-- 64. 대륙 별 사원의 수를 조회한다.
SELECT R.REGION_NAME 
     , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON L.COUNTRY_ID  = C.COUNTRY_ID 
 INNER JOIN REGIONS R
    ON R.REGION_ID = C.REGION_ID 
 GROUP BY R.REGION_NAME 
;

-- 65. 월급이 2500, 3500, 7000 이 아니며 직무가 SA_REP 이나 ST_CLERK 인 사원들의 월급과 직무아이디를 조회한다.
SELECT SALARY
     , JOB_ID
  FROM EMPLOYEES
 WHERE SALARY != 2500  
   AND SALARY != 3500 
   AND SALARY != 7000 
   AND (JOB_ID = 'SA_REP'   
    OR JOB_ID = 'ST_CLERK')
;
-- 65-1 월급이 2500, 3500, 7000이 아닌 사원들의 사원번호와 월급을 조회한다
SELECT EMPLOYEE_ID
     , SALARY
  FROM EMPLOYEES
 WHERE SALARY NOT IN (2500, 3500, 7000)
;
 -- 65-2 직무 ID가 SA_REP 이거나 ST_clerk 인 사원들의 사원번호와 직무 아이디를 조회한다
SELECT EMPLOYEE_ID
     , JOB_ID
  FROM EMPLOYEES
 WHERE JOB_ID IN ('SA_REP', 'ST_CLERK')
;  
-- 65-3 
SELECT SALARY
     , JOB_ID
  FROM EMPLOYEES
 WHERE SALARY NOT IN (2500, 3500, 7000) 
   AND JOB_ID IN ('SA_REP', 'ST_CLERK')
;
-- 66. 사원의 사원번호, 이름, 성, 상사의 사원번호, 상사의 이름, 상사의 성을 조회한다.
SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME 
     , E.LAST_NAME 
     , U.EMPLOYEE_ID 
     , U.FIRST_NAME
     , U.LAST_NAME 
  FROM EMPLOYEES E
 INNER JOIN EMPLOYEES U
    ON E.MANAGER_ID  = U.EMPLOYEE_ID 
;

-- 67. 101번 사원의 모든 부하직원 들의 이름, 성, 상사사원번호, 상사사원명을 조회한다.
SELECT LEVEL
     , E.FIRST_NAME 
     , E.LAST_NAME 
     , E.MANAGER_ID
     , M.FIRST_NAME 
  FROM EMPLOYEES E
 INNER JOIN EMPLOYEES M
    ON E.MANAGER_ID  = M.EMPLOYEE_ID 
 START WITH E.EMPLOYEE_ID = 101
CONNECT BY PRIOR E.MANAGER_ID = E.EMPLOYEE_ID
;

-- 68. 114번 직원의 모든 상사들의 이름, 성, 사원번호를 조회한다.
SELECT LEVEL
     , M.FIRST_NAME 
     , M.LAST_NAME 
     , E.EMPLOYEE_ID 
  FROM EMPLOYEES E 
 INNER JOIN EMPLOYEES M
    ON E.MANAGER_ID = M.EMPLOYEE_ID  
 START WITH E.EMPLOYEE_ID = 114
CONNECT BY PRIOR E.MANAGER_ID = E.EMPLOYEE_ID 

;

-- 69. 114번 직원의 모든 상사들의 이름, 성, 사원번호를 조회한다. 단, 역순으로 조회한다.
SELECT LEVEL
     , M.FIRST_NAME 
     , M.LAST_NAME 
     , E.EMPLOYEE_ID 
  FROM EMPLOYEES E 
 INNER JOIN EMPLOYEES M
    ON E.MANAGER_ID = M.EMPLOYEE_ID  
 START WITH E.EMPLOYEE_ID = 114
CONNECT BY PRIOR E.MANAGER_ID = E.EMPLOYEE_ID 
 ORDER BY LEVEL DESC
;

-- 70. 모든 사원들을 월급 오름차순 정렬하여 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 ORDER BY SALARY ASC
;
-- 71. 모든 사원들을 이름 내림차순 정렬하여 조회한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 ORDER BY LAST_NAME DESC
;
-- 72. 모든 사원들의 이름, 성, 월급, 부서명을 부서번호로 내림차순 정렬하여 조회한다.
SELECT LAST_NAME
     , FIRST_NAME
     , SALARY
     , DEPARTMENT_NAME
  FROM EMPLOYEES
 INNER JOIN DEPARTMENTS
 	ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
 ORDER BY DEPARTMENTS.DEPARTMENT_ID DESC
;

-- 73. 부서명별 월급의 합을 내림차순 정렬하여 조회한다.
SELECT D.DEPARTMENT_NAME
     , SUM(E.SALARY)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME  
 ORDER BY SUM(E.SALARY) ASC 
;
-- 74. 직무명별 사원의 수를 오름차순 정렬하여 조회한다.
SELECT J.JOB_TITLE
     , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN JOBS J 
    ON E.JOB_ID = J.JOB_ID
 GROUP BY J.JOB_TITLE   
 ORDER BY COUNT(E.EMPLOYEE_ID) DESC 
;
-- 75. 모든 사원들의 모든 정보를 조회한다. 단, 인센티브를 받는 사원은 "인센티브여부" 컬럼에 "Y"를, 아닌 경우 "N"으로 조회한다.
-- 76. 모든 사원들의 이름을 10자리로 맞추어 조회한다.
-- 77. 2007년에 직무가 변경된 사원들의 현재 직무명, 부서명, 사원번호, 이름, 성을 조회한다.
SELECT J.JOB_TITLE
     , D.DEPARTMENT_NAME 
     , E.EMPLOYEE_ID 
     , E.FIRST_NAME
     , E.LAST_NAME 
     , JH.END_DATE 
  FROM EMPLOYEES E
 INNER JOIN JOB_HISTORY JH
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
 WHERE JH.END_DATE BETWEEN TO_DATE(2007, 'YYYY') AND TO_DATE(2008, 'YYYY')
;
-- 78. 직무별 최대월급보다 더 많은 월급을 받는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES e
WHERE SALARY > (SELECT MAX(SALARY)
                  FROM EMPLOYEES
                 GROUP BY e.DEPARTMENT_ID)
;


-- 79. 사원들의 이름, 성, 입사연도만 조회한다.
SELECT FIRST_NAME
     , LAST_NAME
     , TO_CHAR(HIRE_DATE, 'YYYY')
  FROM EMPLOYEES
;
-- 80. 사원들의 이름, 성, 연도, 월 만 조회한다.
SELECT FIRST_NAME
     , LAST_NAME
     , TO_CHAR(HIRE_DATE, 'YYYY-MM')
  FROM EMPLOYEES
;


-- 81. 100번 사원의 모든 부하직원을 계층조회한다. 단, LEVEL이 4인 사원은 제외한다.
SELECT LEVEL 
     , EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE LEVEL != 4
 START WITH MANAGER_ID IS NULL
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
 ;

-- 82. 많은 월급을 받는 10명을 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , SALARY
  FROM (SELECT EMPLOYEE_ID
             , FIRST_NAME
             , LAST_NAME
             , SALARY
          FROM EMPLOYEES
         ORDER BY SALARY DESC) E
 WHERE ROWNUM <= 10
;
      
-- 83. 가장 적은 월급을 받는 사원의 상사명, 부서명을 조회한다.
SELECT E.EMPLOYEE_ID
     , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID  
 WHERE E.EMPLOYEE_ID  = (SELECT MANAGER_ID
						   FROM EMPLOYEES
						  WHERE SALARY = (SELECT MIN(SALARY) 
						     			    FROM EMPLOYEES)
    			        )
;
-- 84. 많은 월급을 받는 사원 중 11번 째 부터 20번째를 조회한다.

SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , SALARY
  FROM ( SELECT  EMPLOYEE_ID
		      , FIRST_NAME 
		      , LAST_NAME
		      , SALARY
		      , ROWNUM AS RN
		   FROM EMPLOYEES
		  ORDER BY SALARY DESC)		      
 WHERE RN BETWEEN 11 AND 20
;

-- 85. 가장 적은 월급을 받는 중 90번 째 부터 100번째를 조회한다.

SELECT *
  FROM (
			SELECT EMPLOYEE_ID
			     , FIRST_NAME 
			     , LAST_NAME
			     , SALARY
			     , ROWNUM AS RN
			  FROM ( SELECT  EMPLOYEE_ID
					      , FIRST_NAME 
					      , LAST_NAME
					      , SALARY
					   FROM EMPLOYEES
					  ORDER BY SALARY ASC)) 
 WHERE RN BETWEEN 90 AND 100
;

-- 86. 'PU_CLERK' 직무인 2번째 부터 5번째 사원의 부서명, 직무명을 조회한다.
SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME 
     , E.LAST_NAME
     , E.SALARY
     , E.JOB_ID
     , J.JOB_TITLE 
     , D.DEPARTMENT_NAME 
  FROM ( SELECT  EMPLOYEE_ID
		      , FIRST_NAME 
		      , LAST_NAME
		      , SALARY
     		  , JOB_ID
     		  , DEPARTMENT_ID
		      , ROWNUM AS RN
		   FROM EMPLOYEES
		  WHERE JOB_ID = 'PU_CLERK') E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID
 WHERE RN BETWEEN 2 AND 5
;

-- 87. 모든 사원의 정보를 직무 오름차순, 월급 내림차순으로 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 ORDER BY JOB_ID ASC
     , SALARY DESC
;
-- 88. 부서별 평균월급을 평균월급순으로 오름차순 정렬하여 조회한다.
SELECT DEPARTMENT_ID
     , AVG(SALARY)
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
 ORDER BY AVG(SALARY)
;
-- 89. 부서별 평균월급을 내림차순 정렬하여 조회한다.
SELECT DEPARTMENT_ID
     , AVG(SALARY) AS AVG_SALARY
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
 ORDER BY AVG_SALARY DESC
;
-- 90. 이름의 첫 번째 글자별 평균월급을 조회한다.
-- 하면 안되는거
 SELECT SUBSTR(FIRST_NAME, 1, 1)
      , AVG(SALARY)
   FROM EMPLOYEES E
  GROUP BY SUBSTR(FIRST_NAME, 1, 1)
  ORDER BY SUBSTR(FIRST_NAME, 1, 1) 
;
-- 이런식으로 하는 거 ->
 SELECT LETTER
      , AVG(SALARY)
   FROM ( SELECT SUBSTR(FIRST_NAME,1,1) AS LETTER
               , SALARY
            FROM EMPLOYEES) E 
  GROUP BY LETTER
  ORDER BY LETTER ASC
;  
-- 91. 입사연도별 최소월급을 조회한다.
 SELECT E.YEAR_DATE 
      , MIN(E.SALARY)
   FROM (SELECT TO_CHAR(HIRE_DATE, 'YYYY') AS YEAR_DATE 
              , SALARY
           FROM EMPLOYEES) E
  GROUP BY YEAR_DATE 
  ORDER BY YEAR_DATE ASC
;
-- 92. 월별 최대월급 중 2번째 부터 4번째 데이터만 조회한다.
SELECT HIRE_MONTH 
     , MAX_SAL
  FROM (SELECT HIRE_MONTH 
		     , MAX_SAL
		     , ROWNUM AS RN
		  FROM ( SELECT TO_CHAR(HIRE_DATE , 'MM')  AS HIRE_MONTH
				      , MAX(SALARY) AS MAX_SAL
				   FROM EMPLOYEES
				  GROUP BY TO_CHAR(HIRE_DATE , 'MM') 
				  ORDER BY MAX(SALARY) DESC))
 WHERE RN BETWEEN 2 AND 4
;

-- 93. 직무명별 최소월급을 조회한다.
SELECT JOB_TITLE
     , MIN(SALARY)
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
 GROUP BY JOB_TITLE
;       
 
-- 94. 부서명별 최대월급을 조회한다.
SELECT D.DEPARTMENT_ID
     , MAX(E.SALARY)
  FROM JOBS J
 INNER JOIN EMPLOYEES E
    ON E.JOB_ID  = J.JOB_ID 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID  = E.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_ID
 ;
  
-- 95. 직무명, 부서명 별 사원 수, 평균월급을 조회한다.
SELECT J.JOB_TITLE 
     , D.DEPARTMENT_NAME
     , AVG(SALARY)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON J.JOB_ID  = E.JOB_ID  
 GROUP BY J.JOB_TITLE 
     , D.DEPARTMENT_NAME 
;
-- 96. 도시별 사원 수를 조회한다.
SELECT L.CITY 
     , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID  = D.LOCATION_ID 
 GROUP BY L.CITY 
;
-- 97. 국가별 사원 수, 최대월급, 최소월급을 조회한다.
SELECT C.COUNTRY_NAME
     , COUNT(E.EMPLOYEE_ID) AS EMP_COUNT
     , MAX(SALARY) AS MAXSAL
     , MIN(SALARY) AS MINSAL
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID  = D.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON C.COUNTRY_ID  = L.COUNTRY_ID 
 GROUP BY C.COUNTRY_NAME

 
;

-- 98. 대륙별 사원 수를 대륙명으로 오름차순 정렬하여 조회한다.
SELECT R.REGION_NAME 
     , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID  = D.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON C.COUNTRY_ID  = L.COUNTRY_ID 
 INNER JOIN REGIONS R
    ON R.REGION_ID  = C.REGION_ID    
 GROUP BY R.REGION_NAME 
 ORDER BY R.REGION_NAME ASC

 
-- 99. 이름이나 성에 'A' 혹은 'a' 가 포함된 사원의 모든 정보를 조회한다. COL : 86
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%A%' 
   OR FIRST_NAME LIKE '%a%'
   OR LAST_NAME LIKE '%A%'
   OR LAST_NAME LIKE '%a%'
;
-- 100. 국가별로 월급이 5000 이상인 사원의 수를 조회한다.
SELECT C.COUNTRY_NAME
     , COUNT(E.EMPLOYEE_ID) AS EMP_COUNT 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID  = D.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON C.COUNTRY_ID  = L.COUNTRY_ID 
 WHERE E.SALARY > 5000
 GROUP BY C.COUNTRY_NAME
;

-- 101. 인센티브를 안받는 사원이 근무하는 도시를 조회한다.

-- 102. 인센티브를 포함한 월급이 10000 이상인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM ( SELECT EMPLOYEE_ID
		      , FIRST_NAME 
		      , LAST_NAME
		      , EMAIL
		      , PHONE_NUMBER
		      , HIRE_DATE
		      , JOB_ID
		      , SALARY 
		      , COMMISSION_PCT 
		      , MANAGER_ID 
		      , DEPARTMENT_ID
		      , SALARY + SALARY * NVL(COMMISSION_PCT, 0) AS TOTAL_SALARY
  		   FROM EMPLOYEES) E
  WHERE E.TOTAL_SALARY > 10000
  ORDER BY E.EMPLOYEE_ID 
;
-- 103. 가장 많은 부서가 있는 도시를 조회한다.
SELECT CITY_NAME
  FROM (SELECT L.CITY AS CITY_NAME
		     , COUNT(D.DEPARTMENT_ID) AS EMP_COUNT
		  FROM DEPARTMENTS D
		 INNER JOIN LOCATIONS L
		    ON D.LOCATION_ID = L.LOCATION_ID
		 GROUP BY L.CITY
		 ORDER BY COUNT(D.DEPARTMENT_ID) DESC)
 WHERE ROWNUM = 1
;
 
-- 104. 가장 많은 사원이 있는 부서의 국가명을 조회한다.

SELECT COUNTRY_NAME
  FROM COUNTRIES
 WHERE COUNTRY_ID = (   SELECT COUNTRY_ID
						  FROM LOCATIONS 
						 WHERE LOCATION_ID = (  SELECT LOCATION
												  FROM (SELECT D.DEPARTMENT_ID  AS DEPARTMENT
												  		     , D.LOCATION_ID AS LOCATION
												             , COUNT(E.EMPLOYEE_ID) AS EMP_COUNT
												          FROM DEPARTMENTS D
												         INNER JOIN EMPLOYEES E
												            ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
												         GROUP BY D.DEPARTMENT_ID
												             , D.LOCATION_ID
												         ORDER BY COUNT(E.EMPLOYEE_ID) DESC )
												 WHERE ROWNUM = 1 ))
;



-- 105. 우편번호가 5자리인 도시에서 근무하는 사원명, 부서명, 도시명, 우편번호를 조회한다.
SELECT E.FIRST_NAME
     , D.DEPARTMENT_NAME 
     , L.CITY 
     , L.POSTAL_CODE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE L.POSTAL_CODE LIKE '_____'
;
-- 106. 우편번호에 공백이 없는 도시에서 근무하는 사원의 이름, 부서명, 우편번호를 조회한다.
SELECT E.FIRST_NAME
     , D.DEPARTMENT_NAME 
     , L.CITY 
     , L.POSTAL_CODE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE L.POSTAL_CODE NOT LIKE '% %'
;

-- 107. "주"가 없는 도시에서 근무하는 사원의 이름, 도시를 조회한다.
SELECT E.FIRST_NAME 
     , L.CITY  
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE L.STATE_PROVINCE IS NULL
;
-- 108. 국가명이 6자리인 국가의 모든 정보를 조회한다.
SELECT COUNTRY_ID
     , COUNTRY_NAME
     , REGION_ID
  FROM COUNTRIES
 WHERE COUNTRY_NAME LIKE '______'
;

-- 109. 사원의 이름과 성을 이용해 EMAIL과 같은 값으로 만들어 조회한다.
-- 110. 모든 사원들의 이름을 10자리로 변환해 조회한다. 예> 이름 => "        이름"
-- 111. 모든 사원들의 성을 10자리로 변환해 조회한다. 예> 성 => "성         "
-- 112. 109번 사원의 입사일 부터 1년 내에 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
 WHERE HIRE_DATE BETWEEN (SELECT HIRE_DATE FROM EMPLOYEES WHERE EMPLOYEE_ID = 109) AND ADD_MONTHS((SELECT HIRE_DATE FROM EMPLOYEES WHERE EMPLOYEE_ID = 109), 1 * 12)
;

-- 113. 가장 먼저 입사한 사원의 입사일로부터 2년 내에 입사한사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
 WHERE HIRE_DATE BETWEEN (SELECT MIN(HIRE_DATE) FROM EMPLOYEES) AND ADD_MONTHS((SELECT MIN(HIRE_DATE) FROM EMPLOYEES), 2 * 12)
;
-- 114. 가장 늦게 입사한 사원의 입사일 보다 1년 앞서 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
 FROM EMPLOYEES
WHERE HIRE_DATE <= ADD_MONTHS((SELECT MAX(HIRE_DATE)
				   FROM EMPLOYEES), - 1 * 12)
;		

-- 115. 도시명에 띄어쓰기 " " 가 포함된 도시에서 근무중인 사원들의 부서명, 도시명, 사원명을 조회한다.
SELECT E.FIRST_NAME 
     , L.CITY  
     , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE L.CITY LIKE '% %'
;

-- 116. MOD 함수를 통해 사원번호가 홀수면 남자, 짝수면 여자 로 구분해 조회한다. MOD(값, 나눌값)
-- 117. '20230222' 문자 데이터를 날짜로 변환해 조회한다.(DUAL)
SELECT TO_DATE(20230222, 'YYYYMMDD')
  FROM DUAL
;
-- 118. '20230222' 문자 데이터를 'YYYY-MM' 으로 변환해 조회한다.(DUAL)
SELECT TO_CHAR(TO_DATE(20230222, 'YYYYMMDD'), 'YYYY-MM')
  FROM DUAL
;
-- 119. '20230222130140' 문자 데이터를 'YYYY-MM-DD HH24:MI:SS' 으로 변환해 조회한다. (DUAL)
SELECT TO_CHAR(TO_DATE(20230222130140, 'YYYYMMDDHH24MISS'), 'YYYY-MM-DD HH24:MI:SS')
  FROM DUAL
;
-- 120. '20230222' 날짜의 열흘 후의 날짜를 'YYYY-MM-DD' 으로 변환해 조회한다. (DUAL)
SELECT TO_CHAR(TO_DATE(20230222, 'YYYYMMDD') + 10, 'YYYY-MM-DD')
  FROM DUAL
;

-- 121. 사원 이름의 글자수 별 사원의 수를 조회한다.
 SELECT NAME_LEN 
      , COUNT(EMPLOYEE_ID)
   FROM (SELECT LENGTH(FIRST_NAME) AS NAME_LEN
              , EMPLOYEE_ID
           FROM EMPLOYEES )
  GROUP BY NAME_LEN 
;
-- 122. 사원 성의 글자수 별 사원의 수를 조회한다.
SELECT NAME_LEN 
      , COUNT(EMPLOYEE_ID)
   FROM (SELECT LENGTH(LAST_NAME) AS NAME_LEN
              , EMPLOYEE_ID
           FROM EMPLOYEES )
  GROUP BY NAME_LEN 
;
-- 123. 사원의 월급이 5000 이하이면 "사원", 7000 이하이면 "대리", 9000 이하이면 "과장", 그 외에는 임원 으로 조회한다.
-- 124. 부서별 사원의 수를 조인을 이용해 다음과 같이 조회한다."부서명 (사원의 수)"
-- 125. 부서별 사원의 수를 스칼라쿼리를 이용해 다음과 같이 조회한다. "부서명 (사원의 수)"
-- 126. 사원의 정보를 다음과 같이 조회한다. "사원번호 번 사원의 이름은 성이름 입니다."
-- 127. 사원의 정보를 스칼라쿼리를 이용해 다음과 같이 조회한다. "사원번호 번 사원의 상사명은 상사명 입니다."
-- 128. 사원의 정보를 조인을 이용해 다음고 같이 조회한다. "사원명 (직무명)"
-- 129. 사원의 정보를 스칼라쿼리를 이용해 다음과 같이 조회한다. "사원명 (직무명)"
-- 130. 부서별 월급 차이(최고월급 - 최저월급)가 가장 큰 부서명을 조회한다.

SELECT DEPART_NAME
  FROM (    SELECT D.DEPARTMENT_NAME AS DEPART_NAME
			     , MAX(E.SALARY) AS MAXSAL
			     , MIN(E.SALARY) AS MINSAL
			  FROM EMPLOYEES E
			 INNER JOIN DEPARTMENTS D
			    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
			 GROUP BY D.DEPARTMENT_NAME 
			 ORDER BY (MAXSAL-MINSAL) DESC)
 WHERE ROWNUM = 1
;

-- 131. 부서별 월급 차이(최고월급 - 최저월급)가 가장 큰 부서에서 근무하는 사원들의 직무명을 중복없이 조회한다.
SELECT DISTINCT J.JOB_TITLE 
  FROM EMPLOYEES E 
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
 WHERE E.DEPARTMENT_ID = ( 
							 SELECT DEPART_ID
							  FROM (    SELECT D.DEPARTMENT_NAME AS DEPART_NAME
							                 , D.DEPARTMENT_ID AS DEPART_ID
										     , MAX(E.SALARY) AS MAXSAL
										     , MIN(E.SALARY) AS MINSAL
										  FROM EMPLOYEES E
										 INNER JOIN DEPARTMENTS D
										    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
										 GROUP BY D.DEPARTMENT_NAME 
										     , D.DEPARTMENT_ID
										 ORDER BY (MAXSAL-MINSAL) DESC)
							 WHERE ROWNUM = 1 )
;


-- 132. 부서장이 없는 부서명 중 첫 글자가 'C' 로 시작하는 부서명을 조회한다.
SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE MANAGER_ID IS NULL 
   AND DEPARTMENT_NAME LIKE 'C%'
;
-- 133. 부서장이 있는 부서명 중 첫 글자가 'S' 로 시작하는 부서에서 근무중인 사원의 이름과 직무명, 부서명을 조회한다.
SELECT E.FIRST_NAME 
     , J.JOB_TITLE
     , D.DEPARTMENT_NAME 
  FROM DEPARTMENTS D
 INNER JOIN EMPLOYEES E 
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON E.JOB_ID  = J.JOB_ID 
 WHERE D.DEPARTMENT_NAME  LIKE 'S%'
   AND D.MANAGER_ID IS NOT NULL
;
-- 134. 지역변호가 1000 ~ 1999 사이인 지역내 부서의 모든 정보를 조회한다.
SELECT LOCATION_ID
     , STREET_ADDRESS
     , POSTAL_CODE
     , CITY
     , STATE_PROVINCE
     , COUNTRY_ID
  FROM LOCATIONS
 WHERE LOCATION_ID BETWEEN 1000 AND 1999
;
-- 135. 90, 60, 100번 부서에서 근무중인 사원의 이름, 성, 부서명을 조회한다.
SELECT E.FIRST_NAME
     , E.LAST_NAME
     , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE E.DEPARTMENT_ID IN (90, 60, 100)
;


-- 136. 부서명이 5글자 미만인 부서에서 근무중인 사원의 이름, 부서명을 조회한다.
-- 내가푼거
SELECT E.FIRST_NAME
     , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D         
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID 
 WHERE D.DEPARTMENT_NAME NOT LIKE '_____%'
;

-- INLINE JOIN 사용
SELECT E.FIRST_NAME
     , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
 INNER JOIN (SELECT LENGTH(DEPARTMENT_NAME) AS LEN_NAME
                  , DEPARTMENT_NAME
                  , DEPARTMENT_ID
               FROM DEPARTMENTS) D 
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID
 WHERE D.LEN_NAME < 5


-- 137. 국가 아이디가 'C'로 시작하는 국가의 지역을 모두 조회한다.
SELECT LOCATION_ID
     , STREET_ADDRESS
     , POSTAL_CODE
     , CITY
     , STATE_PROVINCE
     , COUNTRY_ID
  FROM LOCATIONS
 WHERE COUNTRY_ID LIKE 'C%'
;
-- EXTRA 국가명이 'a'로 끝나는 국가의 모든 정보를 조회한다
SELECT COUNTRY_ID
     , COUNTRY_NAME
     , REGION_ID
  FROM COUNTRIES
 WHERE COUNTRY_NAME LIKE '%a'
;
 -- EXTRA 국가명이 'a'로 끝나지 않는 국가의 모든 정보를 조회한다
SELECT COUNTRY_ID
     , COUNTRY_NAME
     , REGION_ID
  FROM COUNTRIES
 WHERE COUNTRY_NAME NOT LIKE '%a'
;
-- 138. 국가 아이디의 첫 글자와 국가명의 첫 글자가 다른 모든 국가를 조회한다.
 SELECT COUNTRY_NAME 
   FROM (SELECT SUBSTR(COUNTRY_ID, 1 ,1) AS COUN_ID
              , COUNTRY_NAME
           FROM COUNTRIES )
  WHERE COUN_ID != SUBSTR(COUNTRY_NAME,1,1)
 ;
-- 139. 사원 모든 정보 중 이메일만 모두 소문자로 변경하여 조회한다.
-- 140. 사원의 월급을 TRUNC(소수점 버림) 함수를 사용해 100 단위는 버린채 다음과 같이 조회한다. 예> 3700 -> 3000, 12700 -> 12000
 SELECT EMPLOYEE_ID 
      , SALARY
      , TRUNC(SALARY, -2)
   FROM EMPLOYEES
;


-- 141. 100단위를 버린 사원의 월급 별 사원의 수를 조회한다.
 SELECT TRUNC_SALARY
      , COUNT(EMPLOYEE_ID)
   FROM (SELECT EMPLOYEE_ID 
              , TRUNC(SALARY, -3) AS TRUNC_SALARY
           FROM EMPLOYEES)
  GROUP BY TRUNC_SALARY 
;
-- 142. 현재 시간으로부터 20년 전 보다 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY
     , COMMISSION_PCT
     , MANAGER_ID
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE HIRE_DATE < ADD_MONTHS(SYSDATE, - 20 * 12)
;
-- 143. 부서번호별 현재 시간으로부터 15년 전 보다 일찍 입사한 사원의 수를 조회한다.
SELECT DEPARTMENT_ID
     , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 WHERE HIRE_DATE <= ADD_MONTHS(SYSDATE, - 15 * 12) 
 GROUP BY DEPARTMENT_ID 
;
-- 144. 부서명, 직무명 별 평균 월급을 조회한다.
SELECT D.DEPARTMENT_NAME 
     , J.JOB_TITLE 
     , AVG(SALARY)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID 
 GROUP BY D.DEPARTMENT_NAME
     , J.JOB_TITLE
;   
  
-- 145. 도시명, 직무명 별 사원의 수를 조회한다.
SELECT L.CITY
     , J.JOB_TITLE 
     , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID  = J.JOB_ID 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID  = D.LOCATION_ID 
 GROUP BY L.CITY 
     , J.JOB_TITLE 
;

-- 146. 부서명, 직무명 별 평균 월급 중 가장 작은 평균월급을 받는 부서명, 직무명을 조회한다.
SELECT DEPAR_NAME
     , JOB_NAME
     , AVG_SAL
  FROM (    SELECT D.DEPARTMENT_NAME  AS DEPAR_NAME
			     , J.JOB_TITLE AS JOB_NAME
			     , AVG(E.SALARY) AS AVG_SAL
			  FROM EMPLOYEES E
			 INNER JOIN DEPARTMENTS D
			    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
			 INNER JOIN JOBS J
			    ON J.JOB_ID  = E.JOB_ID 
			 GROUP BY D.DEPARTMENT_NAME 
			     , J.JOB_TITLE 
			 ORDER BY AVG(E.SALARY) ASC)
 WHERE ROWNUM = 1
;
   

-- 147. 102번 직원의 모든 부하직원의 수를 조회한다.
SELECT COUNT(EMPLOYEE_ID) AS EMPLOYEE_COUNT
  FROM EMPLOYEES
 WHERE LEVEL > 1
 START WITH EMPLOYEE_ID = 102
 CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
;

-- 148. 113번 직원의 모든 부하직원의 수를 조회한다.
SELECT COUNT(EMPLOYEE_ID) AS EMPLOYEE_COUNTER 
  FROM EMPLOYEES 
 WHERE LEVEL > 1
 START WITH EMPLOYEE_ID = 113
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
;
-- 149. 부하직원이 없는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID NOT IN ( SELECT NVL(MANAGER_ID , 0)
   						      FROM EMPLOYEES) 
;

-- 206번 사원의 모든 상식봄위 =
SELECT LEVEL
 	 , EMPLOYEE_ID
     , FIRST_NAME
     , MANAGER_ID
  FROM EMPLOYEES 
 START WITH EMPLOYEE_ID = 206
 CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID
 ORDER BY LEVEL DESC
;
-- 150. 사원번호가 100번인 사원의 사원번호, 이름과 사원번호로 내림차순 정렬된 사원의 사원번호, 이름 조회한다.
/*조회 예
--------------------
100    Steven
206    William
205    Shelley
204    Hermann
203    Susan
202    Pat
201    Michael
200    Jennifer
199    Douglas
198    Donald
197    Kevin
196    Alana
...
*/
